name: Publish purchasely_google (temp)

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  publish-google:
    name: Publish purchasely_google
    permissions:
      id-token: write
      contents: read
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@65eb853c7ba17dde3be364c3d2858773e7144260 # v1
    with:
      environment: pub.dev
      working-directory: purchasely_google
